export const queryKeys = {
  FETCH_SIDEBAR_DOCUMENTS: "FETCH_SIDEBAR_DOCUMENTS",
  DOCUMENT_CREATE: "DOCUMENT_CREATE",
  ARCHIVE_DOCUMENT: "ARCHIVE_DOCUMENT",
  TRASH_DOCUMENTS: "TRASH_DOCUMENTS",
  GET_ALL_DOCUMENTS: "GET_ALL_DOCUMENTS",
  GET_SINGLE_DOCUMENT: "GET_SINGLE_DOCUMENT",
};

export const mutationKeys = {
  UNDO_DOCUMENT: "UNDO_DOCUMENT",
  DELETE_DOCUMENT: "DELETE_DOCUMENT",
  UPDATE_DOCUMENT: "UPDATE_DOCUMENT",
  DELETE_ICON: "DELETE_ICON",
  UPDATE_BANNER: "UPDATE_BANNER",
  UPDATE_CONTENT: "UPDATE_CONTENT",
};
